export const industryCategories = [
    'Advertising Agency',
    'Agriculture, Forestry, Fishing and Poultry',
    'Airlines / GSA',
    'Architecture / Interior Design Firm',
    'Audit Firms / Tax Consultant',
    'Automotive Sales, Support & Service',
    'Bakery',
    'Banks',
    'Banquet / Catering',
    'Beauty, wellness and Grooming',
    'Beverage and Liquor Industries',
    'Biotechnology',
    'BPO / Call Center / ITES',
    'Manufacture and Supplies',
    'Broadcast Media',
    'Business Supplies and Equipment',
    'Cable Television',
    'Capital Market',
    'Construction / Real Estate',
    'Consulting / Legal',
    'Dairy',
    'Designing / Printing / Publishing',
    'Direct Sells / Marketing Service',
    'E-Commerce/ E-Business',
    'Education - School & Colleges',
    'Embassies / Foreign Consulate',
    'Engineering Firms',
    'Event Management',
    'Film/ Motion Picture Production',
    'Finance',
    'Food Production',
    'Gem and Jewellery',
    'Government Organization',
    'Hardware / Network Companies',
    'Health, Wellness and Fitness',
    'Herb and Herbal Product',
    'Hospital / Clinic / Diagnostic Centre',
    'Hotels / Resorts / Restaurant',
    'Hydropower / Alternate Energy',
    'Immigration & Education Consultancy',
    'Import - Export',
    'Information / Computer / Technology',
    'Insurance Company',
    'Investment',
    'ISP',
    'Logistics and Supply Chain',
    'Manpower Recruitment',
    'Media / Publication ',
    'Multinational Company',
    'NGO / INGO / Development Projects',
    'Other',
    'Packaging and Containers',
    'Pharmaceuticals / Healthcare',
    'Real Estate',
    'Recreation and Entertainment',
    'Remittance',
    'Repair/ Maintenance Services',
    'Retail / Shops',
    'Security Service Company',
    'Software Company',
    'Steel and Furniture',
    'Telecommunication',
    'Trading - Export / Import ',
    'Training Institute',
    'Travel Agents / Tour Operators',
    'Journalism / Editor / Media'
]